# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

for file in $HOME/dotfiles/.{aliases}; do
	[ -r "$file" ] && source "$file"
done
unset file

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="steeef"

# Example aliases
 alias ack="nocorrect ack"
 alias irb="irb --readline -r irb/completion"
 alias zshconfig="vim ~/.zshrc"
 alias tmuxconfig="vim ~/.tmux.conf"
 alias ohmyzsh="vim ~/.oh-my-zsh"
 alias vimrc="vim ~/.vimrc"
 alias hosts="vim /etc/hosts"
 alias cl="clear"
 alias redis="redis-server /usr/local/etc/redis.conf"
 alias mysql-server="mysql.server start"
 alias server="python -m SimpleHTTPServer"
 alias composer='nocorrect composer'
 alias tree='nocorrect tree'
 alias z='. ~/z/z.sh'
 alias mux='tmuxinator'
 alias tag='ctags -R --exclude=.git --exclude=log *'

# `cat` with beautiful colors. requires Pygments installed.
# sudo easy_install Pygments
 alias c='pygmentize -O style=monokai -f console256 -g'
 alias ap='pygmentize -O style=monokai -f console256 -g'

 alias localip="ipconfig getifaddr en1"
 alias ips="ifconfig -a | perl -nle'/(\d+\.\d+\.\d+\.\d+)/ && print $1'"

 # Enhanced WHOIS lookups
 alias whois="whois -h whois-servers.net"

 # Flush Directory Service cache
 alias flush="dscacheutil -flushcache"

# # View HTTP traffic
 alias sniff="sudo ngrep -d 'en1' -t '^(GET|POST) ' 'tcp and port 80'"
 alias httpdump="sudo tcpdump -i en1 -n -s 0 -w - | grep -a -o -E \"Host\: .*|GET \/.*\""

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how many often would you like to wait before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git tmuxinator)

. ~/z/z.sh
#### VI MODE ####
#export KEYTIMEOUT=1
#bindkey -v
# Use vim cli mode
bindkey '^P' up-history
bindkey '^N' down-history

# backspace and ^h working even after
# returning from command mode
bindkey '^?' backward-delete-char
bindkey '^h' backward-delete-char

source $ZSH/oh-my-zsh.sh
# Customize to your needs...
export PATH="$PATH:/usr/local/bin:/usr/local/git/bin:/usr/bin:/bin:/usr/sbin:/sbin"
export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
export JAVA_HOME="/usr/libexec/java_home"
export DOCKER_HOST=tcp://192.168.59.103:2375
# go path
export PATH=$PATH:/usr/local/go/bin
export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin
export EDITOR='vim'

#Docker
eval "$(docker-machine env default)"
# Clear unused images
alias dockerrmi="docker images | grep '<none>' | awk '{print $3}' | xargs docker rmi"
alias dockerclear="docker ps -a | grep 'weeks ago' | awk '{print $1}' | xargs --no-run-if-empty docker rm"
